language: python

python:
 - "2.7"
 - "3.6"

env:
 - DJANGO_ENV=django110
 - DJANGO_ENV=django111

install:
 - pip install tox

script:
 - tox -e $(echo py$TRAVIS_PYTHON_VERSION-$DJANGO_ENV | tr -d .)
