# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-09 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def populate_mailing_refs(apps, schema_editor):
    # Migration fails while since the ContentType model is empty at that
    # moment. I guess it's fine to abort the migration, since it's just a data
    # migration anyway.
    if getattr(settings, 'IS_TESTING', True):
        return

    ContentType = apps.get_model('contenttypes', 'ContentType')
    ScheduledJob = apps.get_model('django_future', 'ScheduledJob')
    Mailing = apps.get_model('communication', 'Mailing')

    mailing_ct = ContentType.objects.get(app_label='communication', model='Mailing')
    for job in ScheduledJob.objects.all():
        mailing_id = job.args[0]

        try:
            mailing = Mailing.objects.get(id=mailing_id)
        except Mailing.DoesNotExist:
            # The Mailing referred to by the ScheduledJob, does not exist
            job.delete()
        else:
            # The Mailing referred to by the ScheduledJob, does not refer to
            # the same ScheduledJob
            if not mailing.scheduled_job or mailing.scheduled_job.id != job.id:
                job.delete()
            else:
                job.content_type = mailing_ct
                job.object_id = mailing_id
                job.save()


class Migration(migrations.Migration):
    dependencies = [
        ('django_future', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(populate_mailing_refs),
    ]
