# Generated by Django 1.11.16 on 2019-08-09 08:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_future', '0002_populate_mailing_refs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledjob',
            unique_together={('content_type', 'object_id')},
        ),
    ]
