---
name: Continuous Integration

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python:
          - '3.8'
          - '3.9'
          - '3.10'
        django:
          - 'django32'
          - 'django40'
          - 'django41'

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: ${{ matrix.python }}

      - name: Install `tox`
        run: python -m pip install tox

      - name: Run unit tests
        run: python -m tox -e "py${{ matrix.python }}-${{ matrix.django }}"
