---
name: Python unit tests

on:
  push:
    branches:
  pull_request:
    types: [opened]

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - '3.5'
        django:
          - 'django22'

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install `tox`
        run: python3 -m pip install tox

      - name: Run unit tests
        run: python3 -m tox -e py3-${{ matrix.django }}
